### PR TITLE
Add uri to mongodb VCAP_SERVICES

### PR DESCRIPTION
**Pull request by alainsahli**
Hi

Similarly to PR #123 there should be a credential attribute called uri for the MongoDB service.

### CODE REVIEW

**Comment by rkoster** [comment]
@alainsahli thanks

**Comment by jbayer** [comment]
there is a CLA for @alainsahli but i am pretty sure we have not been requiring that in the past with cloudfoundry-community repos which is less structured. @chipchilders this might be an artifact of the dreddbot following a redirect from a giturl that used to be in a CLA-required github organization like cloudfoundry or cloudfoundry-incubator.

**Comment by chipchilders** [comment]
Very strange. cloudfoundry-community repos are not part of the foundation, so there's no reason that cfdreddbot should be commenting here. @flavorjones or @mmb - Any clue what's up here?

**Comment by drnic** [comment]
Originally the project was @cloudfoundry repo.

**Comment by flavorjones** [comment]
I've added a story to the Toolsmiths backlog to remove this repo from dreddbot's configuration:

> https://www.pivotaltracker.com/story/show/89909126

Should be taken care of in the next few days.

**Comment by chipchilders** [comment]
@flavorjones noted that this isn't a config issue on the foundation side. He's suggested that an admin for this repo in cloudfoundry-community needs to review the webhooks and disable the one talking to @cfdreddbot.

**Comment by jbayer** [comment]
@chipchilders @flavorjones i removed the webhook for dredd

**Pull request merged**
